name: black
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run formatter
        uses: psf/black@stable
        with:
          options: "--check --verbose --line-length 79"
